export const GET_SHOPS_REQUEST = 'GET_SHOPS_REQUEST'
export const GET_SHOPS_LOADED = 'GET_SHOPS_LOADED'
export const GET_SHOPS_REQUEST_ERROR = 'GET_SHOPS_REQUEST_ERROR'

export const REGISTER_SHOP_REQUEST = 'REGISTER_SHOP_REQUEST'
export const REGISTER_SHOP_SUCCESS = 'REGISTER_SHOP_SUCCESS'
export const REGISTER_SHOP_ERROR = 'REGISTER_SHOP_ERROR'
